services:
  backend:
    image: calorie-count:latest
    build:
      context: .
      dockerfile: docker/prod.Dockerfile
    restart: "no"
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/test_db
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: "always"
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123

  adminer:
    image: adminer
    restart: always
    ports:
      - "8085:8085"