server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/test_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true

